name: puremvc
description: "PureMVC Multicore Framework for Dart."
version: 2.1.0
homepage: https://github.com/PureMVC/puremvc-dart-multicore-framework
documentation: https://github.com/PureMVC/puremvc-dart-multicore-framework/doc/api

environment:
  sdk: '>=3.4.4 <4.0.0'

dev_dependencies:
  test: "^1.25.8"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
